### ISSUE TITLE
Error "An instance of screenCap is already running" whenever program is started

### ISSUE THREAD

**Issue by ClementHalim** [goldentoaste/screenCap#3]
Whenever screenCap is opened, the error window pops up saying the program is already started. This occurs at any time the program launches (including when it is not already running), this also occurs when starting automatically on computer startup. It's rather annoying to have to close the popup every time. Closing the program and restarting it results in the program not being able to be opened again as it automatically closes after pressing "OK".

**Comment by goldentoaste** [comment]
@ClementHalim, Thanks for the feedback, this is an issue I have encountered a few times too. I believe this *occasionally* happens when the program is unexpectedly shutdown, for example when forced closed with task manager, Pc loosing power etc. I may look into this in the future.

As a work around for now, please close the program, then navigate to "$appdata%/screenCap" in your windows explorer, and delete a file called "singleton.lock" if there is one. Then restart the program or computer to see if the problem persists.

**Comment by goldentoaste** [comment]
The mentioned has been fixed in the latest release, please download the new one to replace the previous.
